# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConnectExp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConnectExp
  
  pod 'AFNetworking'
  pod 'DateTools'
  pod 'Parse'

  target 'ConnectExpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConnectExpUITests' do
    # Pods for testing
  end

end
